name: nb-decomon-py3.8
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - kaggle
      - pandas
      - decomon==0.0.25
      - --extra-index-url https://test.pypi.org/simple/
