name: nb- decomon==0.0.18
- --extra-index-url https://test.pypi.org/simple/
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
      - decomon==0.0.18
      - --extra-index-url https://test.pypi.org/simple/
